# -*- coding: utf-8 -*-
"""CODSOFT Task 01 - Chatbot with rule based responses.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d-2jBepY2QCxlCgaV_ESLwcQ4Mls4aV3
"""

def chatbot_response(user_input):
    user_input = user_input.lower()
    if "ai" in user_input or "artificial intelligence" in user_input:
        response = "Artificial Intelligence (AI) is the simulation of human intelligence in machines that are capable of learning and performing tasks that typically require human intelligence, such as problem-solving, language understanding, and image recognition."
    elif "machine learning" in user_input or "ml" in user_input:
        response = "Machine Learning is a subset of AI that focuses on the development of algorithms and statistical models that enable computers to improve their performance on a specific task through learning from data."
    elif "deep learning" in user_input or "dl" in user_input:
        response = "Deep Learning is a subfield of machine learning that deals with neural networks containing many layers (deep neural networks). It has been instrumental in achieving significant breakthroughs in tasks like image and speech recognition."
    elif "chatbot" in user_input:
        response = "A chatbot is a computer program that simulates conversation with human users, especially over the internet. They are often used for customer support, information retrieval, and general interaction."
    elif "neural network" in user_input:
        response = "A neural network is a computational model inspired by the structure and function of the human brain. It's used in various AI and machine learning applications."
    elif "natural language processing" in user_input or "nlp" in user_input:
        response = "Natural Language Processing (NLP) is a field of AI that focuses on the interaction between computers and human language. It's used in applications like text analysis, chatbots, and language translation."
    elif "robotics" in user_input:
        response = "Robotics is the study of designing, building, and operating robots. AI plays a significant role in making robots capable of performing tasks autonomously and intelligently."
    elif "reinforcement learning" in user_input:
        response = "Reinforcement Learning is a type of machine learning where an agent learns to make decisions by taking actions in an environment to maximize a reward signal. It's used in scenarios like game playing and autonomous control."
    elif "bye" in user_input:
        response = "Chatbot: Goodbye!"
        return response, True
    else:
        response = "I'm sorry, I don't have information on that topic. Please ask an AI-related question."
    return response, False

print("Chatbot: Hello! How can I assist you with AI today?")
while True:
    user_input = input("You: ").strip()
    response, end_conversation = chatbot_response(user_input)
    print("Chatbot:", response)
    if end_conversation:
        break